In [1]:
import tensorflow as tf

# tensorflow linear transformation example

In [5]:
def get_weights(n_features, n_labels):
    """
    Return TensorFlow weights
    :param n_features: Number of features
    :param n_labels: Number of labels
    :return: TensorFlow weights
    """
    return tf.Variable(tf.truncated_normal((n_features, n_labels)))


def get_biases(n_labels):
    """
    Return TensorFlow bias
    :param n_labels: Number of labels
    :return: TensorFlow bias
    """
    return tf.Variable(tf.zeros(n_labels))


def linear(input, w, b):
    """
    Return linear function in TensorFlow
    :param input: TensorFlow input
    :param w: TensorFlow weights
    :param b: TensorFlow biases
    :return: TensorFlow linear function
    """
    return tf.add(tf.matmul(input, w), b)

In [4]:
from tensorflow.examples.tutorials.mnist import input_data

def mnist_features_labels(n_labels):
    """
    Gets the first <n> labels from the MNIST dataset
    :param n_labels: Number of labels to use
    :return: Tuple of feature list and label list
    """
    mnist_features = []
    mnist_labels = []

    mnist = input_data.read_data_sets('datasets/mnist', one_hot=True)

    # In order to make quizzes run faster, we're only looking at 10000 images
    for mnist_feature, mnist_label in zip(*mnist.train.next_batch(10000)):

        # Add features and labels if it's for the first <n>th labels
        if mnist_label[:n_labels].any():
            mnist_features.append(mnist_feature)
            mnist_labels.append(mnist_label[:n_labels])

    return mnist_features, mnist_labels


# Number of features (28*28 image is 784 features)
n_features = 784
# Number of labels
n_labels = 3

# Features and Labels
features = tf.placeholder(tf.float32)
labels = tf.placeholder(tf.float32)

# Weights and Biases
w = get_weights(n_features, n_labels)
b = get_biases(n_labels)

# Linear Function xW + b
logits = linear(features, w, b)

# Training data
train_features, train_labels = mnist_features_labels(n_labels)

with tf.Session() as session:
    # TODO: Initialize session variables
    session.run(tf.global_variables_initializer())
    
    # Softmax
    prediction = tf.nn.softmax(logits)

    # Cross entropy
    # This quantifies how far off the predictions were.
    # You'll learn more about this in future lessons.
    cross_entropy = -tf.reduce_sum(labels * tf.log(prediction), reduction_indices=1)

    # Training loss
    # You'll learn more about this in future lessons.
    loss = tf.reduce_mean(cross_entropy)

    # Rate at which the weights are changed
    # You'll learn more about this in future lessons.
    learning_rate = 0.08

    # Gradient Descent
    # This is the method used to train the model
    # You'll learn more about this in future lessons.
    optimizer = tf.train.GradientDescentOptimizer(learning_rate).minimize(loss)

    # Run optimizer and get loss
    _, l = session.run(
        [optimizer, loss],
        feed_dict={features: train_features, labels: train_labels})

# Print loss
print('Loss: {}'.format(l))


Extracting datasets/mnist/train-images-idx3-ubyte.gz
Extracting datasets/mnist/train-labels-idx1-ubyte.gz
Extracting datasets/mnist/t10k-images-idx3-ubyte.gz
Extracting datasets/mnist/t10k-labels-idx1-ubyte.gz
Loss: 9.375433921813965


# Tensorflow Softmax example

The softmax function is `tf.nn.softmax()` in TensorFlow.

In [7]:

output = None
logit_data = [2.0, 1.0, 0.1]
logits = tf.placeholder(tf.float32)

# TODO: Calculate the softmax of the logits
softmax = tf.nn.softmax(logits)

with tf.Session() as sess:
    # TODO: Feed in the logit data
    output = sess.run(softmax, feed_dict={logits: logit_data})
    print(output)
    print(output.sum())

[ 0.65900117  0.24243298  0.09856589]
1.0


# One-hot Encoding

In [8]:
import numpy as np
from sklearn import preprocessing

# Example labels
labels = np.array([1,5,3,2,1,4,2,1,3])

# Create the encoder
one_hot_encoder = preprocessing.LabelBinarizer()

# Here the encoder finds the classes and assigns one-hot vectors 
one_hot_encoder.fit(labels)

# And finally, transform the labels into one-hot encoded vectors
one_hot_encoder.transform(labels)
# >>> array([[1, 0, 0, 0, 0],
#            [0, 0, 0, 0, 1],
#            [0, 0, 1, 0, 0],
#            [0, 1, 0, 0, 0],
#            [1, 0, 0, 0, 0],
#            [0, 0, 0, 1, 0],
#            [0, 1, 0, 0, 0],
#            [1, 0, 0, 0, 0],
#            [0, 0, 1, 0, 0]])

array([[1, 0, 0, 0, 0],
       [0, 0, 0, 0, 1],
       [0, 0, 1, 0, 0],
       [0, 1, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 1, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 0, 1, 0, 0]])

# Cross Entropy in TensorFlow

In [21]:
softmax_data = [0.7, 0.2, 0.1]
one_hot_data = [1.0, 0.0, 0.0]

softmax = tf.placeholder(tf.float32)
one_hot = tf.placeholder(tf.float32)

def cross_entropy(softmax_score_vector, prediction_vector):
    return -1 * tf.reduce_sum(tf.multiply(prediction_vector, tf.log(softmax_score_vector)))

with tf.Session() as session:
    output = session.run(cross_entropy(softmax, one_hot), feed_dict={softmax: softmax_data, one_hot: one_hot_data})
    print(output)

0.356675
